feat: add function for app name to local storage
calimero-is-near/VM pull request #9
Opened 2023-08-14 12:40 UTC by frdomovic

## feat: add function for app name to local storage
Added function to save app name to private storage -> as widgetSrc is unavailable and not sure how are they passing it. (logging it returns undefined) 
Usage: 
<img width="247" alt="Screenshot 2023-08-14 at 14 39 22" src="https://github.com/calimero-is-near/VM/assets/93442516/13af49ed-927d-4e75-931c-1a7f9aa1a549">
Keys saved with appName prefix
<img width="383" alt="Screenshot 2023-08-14 at 14 16 54" src="https://github.com/calimero-is-near/VM/assets/93442516/e2eb58eb-ce31-46aa-8e0d-252e4f6b24b0">

2023-08-14 13:42 UTC, xilosada commented
My concern with this approach is that someone creates an App which uses the same appName. The user may don't want to give access to the new app but they still can use the fak.

2023-08-14 13:43 UTC, xilosada requested changes
Check my previous comment

2023-08-16 03:25 UTC, xilosada reviewed
Can you update the description of the PR and include the change? Also squash the commits(locally or change the project settings

2023-08-16 03:25 UTC, xilosada commented on src/lib/vm/vm.js
> +        const componentName = this.vm.widgetSrc.replace("/widget/","-");
Why are u using replace here?

2023-08-16 13:29 UTC, frdomovic commented on src/lib/vm/vm.js
> +        const componentName = this.vm.widgetSrc.replace("/widget/","-");
Reverted as adding widgetSrc worked as well

2023-08-16 13:29 UTC, merged